server:
  port: 8083

spring:
  application:
    name: simulation-service
  profiles:
    active: local
    group:
      docker: "kafka,topics"
  config:
    import: optional:configserver:http://localhost:8888
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://localhost:5432/simulationdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1
  model: gpt-4o-mini
  timeout:
    connect: 5000
    read: 30000
